version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    expose: [3306]
    environment:
      MYSQL_ROOT_PASSWORD: start123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user